cmake_minimum_required(VERSION 3.16)
project(esp32_contract_host LANGUAGES CXX)
add_executable(esp32_contract_host main.cpp)
target_compile_features(esp32_contract_host PRIVATE cxx_std_17)
# Need sin()
target_link_libraries(esp32_contract_host PRIVATE)
if(NOT WIN32)
  target_link_libraries(esp32_contract_host PRIVATE m)
endif()
